language: java
jdk:
    - oraclejdk8

script: ant build

addons:
    sonarcloud:
        organization: "cp-jwu130-github"
        token:
            secure: travis encrypt fb9494fcdb69e66c9e6a444e799f98b91de36de3
    script:
        - sonar-scanner
