language: java
jdk:
    - oraclejdk8

script: ant build

addons:
    sonarcloud:
        organization: "cp-jwu130-github"
        token:
            secure: SONAR_KEY
    script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
